### ISSUE TITLE
Exporting MutationConfig

### ISSUE THREAD

**Issue by Un3qual** [relay-tools/relay-hooks#105]
Could `MutationConfig` and other types that are different from those exposed in `relay-runtime` be exported from the library?

**Comment by morrys** [comment]
Hi @Un3qual,
sorry for the delay in answering but it's vacation time :)

Indeed they **must** be exported. The idea was to put all the types into [RelayHooksType](https://github.com/relay-tools/relay-hooks/blob/master/src/RelayHooksType.ts) so as to [export them all](https://github.com/relay-tools/relay-hooks/blob/master/src/index.ts#L24).

Besides MutationConfig, have you identified any others?

**Comment by morrys** [comment]
This issue has been resolved with the newly released version [3.6.0](https://github.com/relay-tools/relay-hooks/releases/tag/v3.6.0).
