### ISSUE TITLE
[typescript]: Response types from relay complier

### ISSUE THREAD

**Issue by saihaj** [relay-tools/relay-hooks#110]
I am trying to use this `useQuery` with typescript. I want to use types generated by `relay-compiler`. Can someone please help me 🙏🏼 

![image](https://user-images.githubusercontent.com/44710980/90575353-d000d380-e180-11ea-832d-8872b861084a.png)

Edit: GitHub repo https://github.com/saihaj/cra-relay-typescript/blob/dev/src/components/Character/Card.tsx

**Comment by renanmav** [comment]
You should use like this `useQuery<CardCharacterQuery>(query, variables)`

**Comment by saihaj** [comment]
> You should use like this `useQuery<CardCharacterQuery>(query, variables)`

I get typescript errors 
![image](https://user-images.githubusercontent.com/44710980/90576850-eb6ddd80-e184-11ea-8e07-d6a49ab4b519.png)

**Comment by renanmav** [comment]
@saihaj `CardCharacterQuery`, not `CardCharacterQueryResponse`

**Comment by saihaj** [comment]
@renanmav thanks you so much!!
