### ISSUE TITLE
useQuery: flash of 'old' data after updating variables

### ISSUE THREAD

**Issue by Togrias** [relay-tools/relay-hooks#12]
when I pass some variables into useQuery(), and variables updates, useQuery still returns the old result from the previous variables in its first render. 

It immediately triggers a re-render, but this can still mess up components which depend on whether the data is loading. i.e. const isLoading = !props, because the result implies that the new data is ready, but is in fact still loading.

**Comment by morrys** [comment]
Hi Togrias,
what version of relay-hooks are you using?

**Comment by Togrias** [comment]
1.2.0

**Comment by morrys** [comment]
Hi Togrias,
I did tests and useQuery seems to behave correctly.
Can you modify the example project or send me a gist that allows me to recreate the problem?

**Comment by Togrias** [comment]
I'm not familiar with graphql.js but it seems fairly easy to replicate.
pass a variable (v1) to useQuery, change it to some other value (v2) after 5 seconds. At the exact moment of the change, useQuery({ variables: v2 , query: ... }) will still return the old result of v1. It will trigger an immediate re-render.

This doesn't happen with <QueryRenderer/>.

**Comment by morrys** [comment]
Hi Togrias,
last night I recreated the problem in the example project and implemented its first resolution.
By tonight I hope to create the branch with the changes made.

I need to perform further checks and tests before releasing version 1.2.1.

**Comment by morrys** [comment]
Hi Togrias,
the problem is clear but I am evaluating cleaner and more maintainable solutions.
I hope to release version 1.2.1 this weekend.

Thank you,
Lorenzo

**Comment by morrys** [comment]
Hi Togrias,
I just released version 1.2.1 of relay-hooks which fixes the problem you detected.

I await your confirmation to close the issue.

Thank you,
Lorenzo

**Comment by Togrias** [comment]
Hi,

I just tested it. Yes, the issue is resolved. Thanks!
