### ISSUE TITLE
Is there a way to use networkCacheConfig and metadata in UseMutation?

### ISSUE THREAD

**Issue by o-gi** [relay-tools/relay-hooks#122]
I can pass the networkCacheConfig to QueryOptions in useQuery, but I don't know how to do it in UseMuation.

I may have missed something?

**Comment by sibelius** [comment]
check here https://github.com/facebook/relay/pull/3070

**Comment by morrys** [comment]
look this issue: https://github.com/relay-tools/relay-hooks/issues/97

**Comment by morrys** [comment]
Perhaps what's missing is the parameter in @types/relay-runtime. I just created the PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48858 which fixes this problem

**Comment by o-gi** [comment]
Thank you guys for your response and PR for fix this problem.

**Comment by alloy** [comment]
The DT PR has been merged.

**Comment by morrys** [comment]
thanks @alloy 👍
