### ISSUE TITLE
During retry/refetch props are null with "store-and-network"

### ISSUE THREAD

**Issue by olso** [relay-tools/relay-hooks#123]
This is the query

**lib versions**  

```json
"relay-hooks": "^3.7.0",
"relay-runtime": "^10.0.1",
"react-relay": "^10.0.1",
"react-relay-network-modern": "^5.0.1",
"react-relay-network-modern-ssr": "^1.4.0",
```

```tsx
cacheMiddleware({
        size: 80, // I've tried something like 999999 just to be sure
        ttl: MINUTE * 5,
        clearOnMutation: false
      }),
```

```tsx
const { props } = useQuery<MessageListQuery>(
    graphql`
      query MessageListQuery($chatId: ID!) {
        messages(chatId: $chatId) {
          edges {
            node {
              id
              ...MessageListItem_message
            }
          }
        }
        chat(id: $chatId) {
          marina {
            ...MessageListItem_marina
          }
        }
      }
    `,
    { chatId },
    {
      fetchPolicy: "store-and-network",
      networkCacheConfig: { poll: 15000 },
      fetchKey: `${updatedAt}`,
    },
  );
```

When the `fetchKey` changes (after mutation), `props` are `null` for one render cycle, making the interface blink. I'm I doing something wrong? I thought `store-and-network` keeps the **old** `props` while fetching new props

https://relay.dev/docs/en/a-guided-tour-of-relay#fetch-policies

> "store-and-network": will reuse locally cached data and will always send a network request, regardless of whether any data was missing or stale in the store.

**Comment by morrys** [comment]
To be precise, store-and-network at the first render does **not show the old props but the data present in the store.**

I recommend that you check the behavior of the library [here](https://github.com/relay-tools/relay-hooks/blob/master/src/QueryFetcher.ts#L144) as well as verify that the store still contains the necessary data for the [lookup to be available](https://github.com/relay-tools/relay-hooks/blob/master/src/QueryFetcher.ts#L92)

**Comment by olso** [comment]
@morrys somehow it works now, the only thing I've changed in the meantime is move the mutation up the tree (into parent)

But now I have different issue with `store-and-network`, I'm digging throught debugger now

I'm getting logs that say the query was done in **12ms** which means, its not actually hitting the server and is local

```
[RELAY-NETWORK] Done MessageListQuery in 12ms
```

and the `Network` tab in dev tools isnt seeing any activity

**Comment by olso** [comment]
@morrys Found the culprit, its the `cacheMiddleware` it is not respecting `store-and-network`
