### ISSUE TITLE
refetch connection from usePagination hook

### ISSUE THREAD

**Issue by skk2142** [relay-tools/relay-hooks#124]
I'm using `refetchConnection` from `usePagination` hook as shown in the component below inside the `useEffect` hook.  I do see that the graphql query is being fetched when the `useEffect` hook runs. However, the component does not re-render. So it keeps showing the old data. Am I doing something wrong? 

```typescript
const connectionConfig: ConnectionConfig<{}> = {
  getVariables: (props, { count, cursor }) => {
    return {
      count,
      cursor,
    };
  },
  query: graphql`
    query RepositoryList_PaginationQuery($count: Int!, $cursor: String) {
      viewer {
        ...RepositoryList_viewer @arguments(count: $count, cursor: $cursor)
      }
    }
  `,
};
export const RepositoryList = (props: {
  viewer: RepositoryList_viewer$key;
}) => {
  const [viewer, { loadMore, refetchConnection }] = usePagination<
    RepositoryList_viewer$key,
    RepositoriesPaginationQuery
  >(
    graphql`
      fragment RepositoryList_viewer on User
      @refetchable(queryName: "RepositoriesPaginationQuery")
      @argumentDefinitions(
        count: { type: "Int!", defaultValue: 5 }
        cursor: { type: "String", defaultValue: null }
        orderBy: {
          type: "RepositoryOrder"
          defaultValue: { field: PUSHED_AT, direction: DESC }
        }
      ) {
        repositories(first: $count, after: $cursor, orderBy: $orderBy)
          @connection(key: "RepositoryList_viewer_repositories") {
          edges {
            node {
              ...Repository_repo
              id
            }
          }
        }
      }
    `,
    props.viewer
  );
  const [isChecked, setIsChecked] = useState(false);
  const mounted = useRef(false);
  useEffect(() => {
    setTimeout(() => {
      mounted.current = true;
    }, 0);
  }, []);
  useEffect(() => {
    if (!mounted.current) {
      return;
    }
    refetchConnection(
      {
        query: graphql`
          query RepositoryList_orderRefetch_Query(
            $orderBy: RepositoryOrder!
            $count: Int!
            $cursor: String
          ) {
            viewer {
              ...RepositoryList_viewer
                @arguments(count: $count, cursor: $cursor, orderBy: $orderBy)
            }
          }
        `,
        getVariables: (p, { count, cursor }, fragVars) => {
          return {
            count,
            cursor,
            orderBy: isChecked
              ? { field: 'PUSHED_AT', direction: 'ASC' }
              : { field: 'PUSHED_AT', direction: 'DESC' },
          };
        },
      },
      10,
      undefined
    );
  }, [isChecked]);
  // const source = useRelayEnvironment().getStore().getSource().get(viewer.id);
  // if (source) {
  //   ConnectionHandler.getConnection(source, '')
  // }
  return (
    <div>
      <h1 className="text-brand-600">Blog posts</h1>
      <label htmlFor="order">Order: Last pushed last</label>
      <input
        type="checkbox"
        className="form-checkbox"
        name="order"
        id="order"
        checked={isChecked}
        onChange={(e) => setIsChecked(e.currentTarget.checked)}
      ></input>
      <ul>
        {viewer.repositories.edges?.map(
          (e) => e?.node && <Repository key={e.node.id} post={e.node} />
        )}
      </ul>
      <button
        className="text-xl border p-2 bg-indigo-700 text-white"
        onClick={() => loadMore(connectionConfig, 5)}
      >
        Load more friends
      </button>
    </div>
  );
};

```

**Comment by morrys** [comment]
Hi @skk2142,
it would be useful to have a test case/sample project that detects the problem so that I can help you better understand where the problem is.

If you do not have the time or opportunity to do so I ask you to try to send more information.

This is where the hook data is updated following the refetch:
https://github.com/relay-tools/relay-hooks/blob/5b439adad362c143b9097f5c8508f2d3dcb949fb/src/FragmentResolver.ts#L408-L429

Add logs here to see its behavior

**Comment by skk2142** [comment]
It's difficult to share the project so I will share more details. If you see the fragment, it is using `{ field: PUSHED_AT, direction: DESC }` as the `orderBy` default variable. When the `refetchConnection` is triggered inside the second `useEffect` hook, the `orderBy` variable being used is `{ field: 'PUSHED_AT', direction: 'ASC' }`. The data is fetched for this new variable. It also triggers this line. https://github.com/relay-tools/relay-hooks/blob/5b439adad362c143b9097f5c8508f2d3dcb949fb/src/FragmentResolver.ts#L430
However, the fragment still uses the previously fetched data. My hunch is that `usePagination` is not using the variables used in `refetchConnection`. Please let me know if I can share more details. Happy to show my code on zoom screen share if you want. Thanks so much.

**Comment by morrys** [comment]
Can you tell me how the hook behaves after updating in this function?

https://github.com/relay-tools/relay-hooks/blob/5b439adad362c143b9097f5c8508f2d3dcb949fb/src/FragmentResolver.ts#L140-L144

**Comment by morrys** [comment]
I close the issue due to inactivity, I suppose the problem has been solved
