### ISSUE TITLE
next-ssr with useRouter/withRouter

### ISSUE THREAD

**Issue by fi0** [relay-tools/relay-hooks#130]
In /examples/relay-hook-example/nextjs-ssr/pages/index.tsx
How do I pass a queryString (from useRouter/withRouter) to variables.userId ?
Thank you!

**Comment by taion** [comment]
Use `prepareVariables` on the route.

**Comment by fi0** [comment]
I'm using nextjs's dynamic routing with relay-hooks. Is it possible to use `prepareVariables` and `withData` from the example?
