### ISSUE TITLE
networkCacheConfig does not work in useQuery

### ISSUE THREAD

**Issue by aleksandrlat** [relay-tools/relay-hooks#143]
`networkCacheConfig` is passed to `fetchQuery` here https://github.com/relay-tools/relay-hooks/blob/v3.7.0/src/QueryFetcher.ts#L179-L182

This `fetchQuery` is internal https://github.com/relay-tools/relay-hooks/blob/v3.7.0/src/QueryFetcher.ts#L14

And `fetchQueryInternal` does not accept 3rd parameter https://github.com/facebook/relay/blob/master/packages/relay-runtime/query/fetchQueryInternal.js#L105-L108

I don't know why `fetchQueryInternal` is used. But maybe we should use regular `fetchQuery`?

Or should we pass `networkCacheConfig` to `createOperationDescriptor` here https://github.com/relay-tools/relay-hooks/blob/v3.7.0/src/Utils.ts#L48?

**Comment by morrys** [comment]
Hi @aleksandrlat,
relay-hooks 3.7.0 does not support relay-runtime v10, so you have to look at the fetchQuery at version 9:
https://github.com/facebook/relay/blob/v9.1.0/packages/relay-runtime/query/fetchQueryInternal.js#L106-L112

Relay-runtime v10 support is being released with version 4.0.0 https://github.com/relay-tools/relay-hooks/issues/126

Currently version 4.0.0-rc.3 is already available

**Comment by aleksandrlat** [comment]
@morrys got it. Thank you very much!
