### ISSUE TITLE
Migration advices from version 3 to version 4

### ISSUE THREAD

**Issue by aleksandrlat** [relay-tools/relay-hooks#144]
@morrys I just noticed you released stable version 4.
Great work! Thank you!

Do you have any advices for migrating from version 3.7.0 to version 4.0.0?

Or this is enough to know?
```
Breaking Changes
- removed support to Mutation HOC
- useRefetch no longer exists
- remove fetchObserver in useQuery in favor of onComplete property
- changed the return type:
  - useQuery -> const { data, isLoading, error, retry} = useQuery(query, variables); (removed cached and added isLoading)
  - useRefetchable -> const { data, refetch, isLoading, error } = useRefetchable(node, ref); (before [data, refetch])
  - usePagination -> const { data, hasNext, isLoadingNext, hasPrevious, isLoadingPrevious, isLoading, refetch, loadNext, loadPrevious, errorNext, errorPrevious, error } = usePagination(node, ref); (before [ data, { isLoading, hasMore, loadMore } ])
- usePagination now uses the @refetchable directive
```

Thanks in advance!

**Comment by morrys** [comment]
Hi @aleksandrlat,
in these two PRs I made the migrations of 2 example projects:
https://github.com/relay-tools/relay-hooks/pull/133/files
https://github.com/relay-tools/relay-hooks/pull/134/files

We can use this issue to add useful information to the migration.

**Comment by aleksandrlat** [comment]
Main change for us is `useQuery` returns `data` now instead of `props`

**Comment by morrys** [comment]
> Also I could not migrate usePagination yet because our fragment is not "refetchable". I will return back to it later.

Could you explain better?

**Comment by n1ru4l** [comment]
I just migrated and the new usePagination hook is so much nicer! The `@refetchable` directive is super powerful!

**Comment by morrys** [comment]
I close the issue as the most used version of relay-hooks is 4.2.0
