### ISSUE TITLE
How to use usePagination, useFragment, useRefetch with root level queries?

### ISSUE THREAD

**Issue by harryy2510** [relay-tools/relay-hooks#15]
I am trying to paginate a root level query, not really sure how to do it. I went through all the examples but couldn't find a way to achieve it.

Parent component

```
import React, {FunctionComponent} from 'react';
import useQuery from 'relay-hooks/lib/useQuery';
import {graphql} from 'relay-runtime';
import Child from './Child';

const Parent: FunctionComponent = () => {
    const {props} = useQuery({
        query: graphql`
            query FragmentTestQuery($first: Int, $after: String) {
                ...ChildFragment
            }
        `,
        variables: {
            first: 100,
            after: ''
        }
    });
    return <Child {...props}/>
};

export default Parent
```

Child component

```
import React, {FunctionComponent} from 'react'
import usePagination from 'relay-hooks/lib/usePagination';
import {graphql} from 'relay-runtime';

const fragmentSpec = graphql`
    fragment ChildFragment on Query {
        users(first: $first, after: $after) {
            nodes {
                node {
                    id
                    firstName
                    lastName
                }
                position
            }
            pageInfo {
                hasNext
                hasPrevious
            }
        }
    }
`;

const Child: FunctionComponent<any> = props => {
    const fragmentProps = usePagination(fragmentSpec, props);
    console.log(fragmentProps);
    return (
        <div>Test</div>
    )
}

export default Child
```

**Comment by morrys** [comment]
hi harryy2510,
you can try to change:
 `return <Child {... props} />` 
in 
`return <Child query = {props} />`

and 

`const fragmentProps = usePagination (fragmentSpec, props);` 
in
`const fragmentProps = usePagination (fragmentSpec, props.query);`

also, you can import hooks like this:
import {useQuery, usePagination, useRefetch, useMutation} from 'relay-hooks';

Let me know,
Lorenzo

**Comment by sibelius** [comment]
useQuery still needs to have a context provider?

**Comment by harryy2510** [comment]
@morrys I tried doing as mentioned, but got an empty object instead. Not really sure where am I going wrong.

![image](https://user-images.githubusercontent.com/7416971/61157210-1c57f980-a513-11e9-8b6a-63891694ca4c.png)

**Comment by morrys** [comment]
hi harryy2510,
I created your use case in the root_level branch and with the solution that I showed you the data is correctly retrieved from the usePagination.

https://github.com/relay-tools/relay-hooks/commit/2f0af2fc0e8da2d4e031a67eccf5850604e122bb

Are you sure to retrieve data correctly from the server?

Lorenzo

**Comment by harryy2510** [comment]
@morrys  Data is retrieved correctly. I'm still investigating the issue. Thanks for your help :) 
I am closing the issue for now. Will get back if still persists.
