### ISSUE TITLE
After skip query is disposed and not retained any more

### ISSUE THREAD

**Issue by aleksandrlat** [relay-tools/relay-hooks#152]
Looks like some issue after query is skipped in new version 4

Steps to reproduce:
- run query as usual: `const { retry } = useQuery(query, {}, { skip: false })`
- skip query: `const { retry } = useQuery(query, {}, { skip: true })`
  - after we skip query it is disposed https://github.com/relay-tools/relay-hooks/blob/v4.0.0/src/QueryFetcher.ts#L163
  - and data is garbage collected by relay store
- run same query again: `const { retry } = useQuery(query, {}, { skip: false })`
  - it is still disposed but `QueryFetcher` returns previously saved `QueryFetcher.result`
  - no data in relay store
- retry request now with `retry` function returned by `useQuery` above
  - but when we retry now operation is not retained in `FetchResolver` because of this condition https://github.com/relay-tools/relay-hooks/blob/v4.0.0/src/FetchResolver.ts#L117
  - `environment` and `query.request.identifier` are the same
  - relay does not retain data in store
  - we subscribe to snapshot updates anyway and snapshot subscription is alive
- make any other query
  - our snapshot receives update but with missing data now because relay didn't retain data for it

Steps are complex and this case is rare. But looks like I debugged it correctly.
I think there maybe other scenarios when query is not retained after it is disposed on skip because of this condition https://github.com/relay-tools/relay-hooks/blob/v4.0.0/src/FetchResolver.ts#L117

**Comment by morrys** [comment]
hi @aleksandrlat, thanks for your detailed debugging 👍 

I created this PR https://github.com/relay-tools/relay-hooks/pull/153 in draft which should fix your problem.

it is in draft because I have to do further tests but it would be very useful to have your feedback

**Comment by morrys** [comment]
released with version [4.1.0](https://github.com/relay-tools/relay-hooks/releases/tag/v4.1.0 )
