### ISSUE TITLE
relay-hooks version 4.1.0

### ISSUE THREAD

**Issue by morrys** [relay-tools/relay-hooks#155]
# Improved
  * [X] useSubscription, feat: add a skip option for useSubscription https://github.com/relay-tools/relay-hooks/pull/148
  * [X] useMutation, removed the MutationConfigWithVariables type as it is not needed https://github.com/relay-tools/relay-hooks/pull/149
  * [x] useMutation, set mutation data with optistimicResponse while the mutation is in flight https://github.com/relay-tools/relay-hooks/pull/150

# Fixed
  * [x] useQuery, fix skip & dispose fetcher https://github.com/relay-tools/relay-hooks/pull/153
  * [x] loadQuery, unsubscribe only if the callback function is still subscribed https://github.com/relay-tools/relay-hooks/pull/154

**Comment by aleksandrlat** [comment]
Thank you @morrys!
Do you have an idea when this version will be released?

**Comment by morrys** [comment]
@aleksandrlat right now :)
https://github.com/relay-tools/relay-hooks/releases/tag/v4.1.0
