### ISSUE TITLE
useFragment returns `unknown` type

### ISSUE THREAD

**Issue by MoSattler** [relay-tools/relay-hooks#158]
`useFragment` does not work with [typescript relay](https://github.com/relay-tools/relay-compiler-language-typescript). 

In this case, the type of `user` is unknown.
```
interface Props {
  user: MyComponent_user;
}

const MyComponent = (props: Props) => {
  const user = useFragment(fragmentSpec, props.user);
  return null
}
```

**Comment by morrys** [comment]
hi @MoSattler,
as you can see in the [documentation](https://github.com/relay-tools/relay-hooks/blob/master/docs/useFragment.md#arguments ) and / or [sample project](https://github.com/relay-tools/relay-hooks/blob/master/examples/relay-hook-example/pagination-nextjs-ssr/components/Todo.tsx#L27), you must use the type of the key.
