### ISSUE TITLE
support for plural fragments?

### ISSUE THREAD

**Issue by Togrias** [relay-tools/relay-hooks#17]
It appears that useFragment does not fetch list fragments properly i.e. @relay(plural: true). It returns a blank object.

**Comment by morrys** [comment]
Hi Togrias,
can you recreate the error in the example project? otherwise I will provide as soon as possible.

Thank you,
Lorenzo

**Comment by morrys** [comment]
in the root_level branch I modified the example project and the relay (plural: true) seems to work correctly.

Can you take a look at the commit or some more information about your use case?

thanks

**Comment by Togrias** [comment]
Hi,
I don't quite understand the following:
`  const nodes: $ReadOnlyArray<Node> =
  edges 
      ? Object.values(edges).map((edge: Edge) => edge.node)
      : [];
`
So useFragment() on a plural fragment definition is supposed to return an object? 

It didn't occur to me to use Object.values(pluralFragment)

For the createFragmentContainer HOC, a plural fragment definition would take an array prop and supply an array to the wrapped component.

If useFragment's intended behaviour is different from createFragmentContainer, perhaps it's a good idea to specify. Otherwise, please feel free to close this issue.

**Comment by morrys** [comment]
thank you for identifying this difference, the behavior does not want to be different.

I leave the issue open because these days I try to fix the difference.

you will soon have my news,
Lorenzo

**Comment by morrys** [comment]
Hi Togrias,
I have just published version 1.2.2 where the array is returned.

I have also modified the sample project of the branch and it works correctly:

https://github.com/relay-tools/relay-hooks/commit/da52f30280388b3ccd31ea9822dc29dd09c5a148

I await your confirmation to close the issue.
Thank you,
Lorenzo
