### ISSUE TITLE
Type errors when using Relay 13

### ISSUE THREAD

**Issue by kesne** [relay-tools/relay-hooks#199]
Relay 13 was released, and it looks like the types for `useFragment` broke due to the generated code changing from `$fragmentRefs` to `$fragmentSpreads`.

**Comment by morrys** [comment]
Hi @kesne,
thanks for the tip.

in these days, after recovering from the holidays, I will create the compatibility branch to relay v13 👍

**Comment by morrys** [comment]
Hi @kesne,
PR for v13 relay support is in draft https://github.com/relay-tools/relay-hooks/pull/201.
The modification to the sources seems trivial while adapting the tests to use the new compiler in rust still requires some work.

**Comment by morrys** [comment]
fixed with version [7.0.0](https://github.com/relay-tools/relay-hooks/releases/tag/v7.0.0)
