### ISSUE TITLE
Example integration with next.js

### ISSUE THREAD

**Issue by pradel** [relay-tools/relay-hooks#21]
Hey, thanks for this great tool!
I was wondering if somebody successfully integrated relay-hooks with next.js and have an ssr working example to share :)

**Comment by morrys** [comment]
Hi @pradel,
the request is certainly interesting, but these days I have to prioritize documentation with docusaurus of all my repositories that extend Relay's functionality.
* relay-hooks
* [wora](https://github.com/morrys/wora)
* [react-relay-offline](https://github.com/morrys/react-relay-offline)
* [react-relay -appsync](https://github.com/morrys/react-relay-appsync)

In the meantime let's see if anyone in the community can contribute to its realization :)

Lorenzo

**Comment by Bastiani** [comment]
Hi @pradel,
I'm doing my personal blog and trying to hook, but useRefetch did not return data https://github.com/Bastiani/bastiani-blog/pull/4

**Comment by morrys** [comment]
hi @pradel,
today I released version 2.1.0 and created within this repository an example project in nextjs-ssr with typescript
https://github.com/relay-tools/relay-hooks/tree/master/examples/relay-hook-example/nextjs-ssr

For any problem, open a new issue :)
thanks
