### ISSUE TITLE
RelayContext: Expected context.relay to be an object conforming to the RelayContext interface

### ISSUE THREAD

**Issue by jckw** [relay-tools/relay-hooks#22]
React Relay v5.0.0 removes `environment.unstable_internal` [here](https://github.com/facebook/relay/commit/a0b43393751a872c2665c467d148593d68a689a5). This makes v5 incompatible with relay-hooks because it is [used in the UseQueryFetcher class](https://github.com/relay-tools/relay-hooks/blob/master/src/UseQueryFetcher.ts#L51). 

The dependencies for this package could be updated to force a react-relay version below 5.0.0, or the code would need to be refactored to allow react-relay v5.0.0 users to continue using the package.

**Comment by morrys** [comment]
Hi @jckw,
to version 5.0.0 environment.unstable_internal is still used as you can see [here](https://github.com/facebook/relay/blob/v5.0.0/packages/react-relay/ReactRelayFragmentContainer.js#L61) and the library works correctly with this version.

did you find any errors?

Lorenzo

**Comment by jckw** [comment]
Yep, looks like this was my fault for not passing in the correct Relay environment. 🤦‍♂️

Now getting a different, but possibly unrelated error:

```
RelayContext: Expected `context.relay` to be an object conforming to the `RelayContext` interface, got `[object Object]`.
```

**Comment by morrys** [comment]
It seems a problem of backward compatibility by performing a migration from above.

Now I'm on vacation until August 20th and I can't make changes / tests. Can you try using this as a provider?

```ts
import * as React from 'react';
import { ReactRelayContext } from 'react-relay';
import {
    Environment,
  } from 'relay-runtime';


const RelayEnvironmentProvider = function (props: {children: React.ReactNode, environment?: Environment})  {

    RelayFeatureFlags.PREFER_FRAGMENT_OWNER_OVER_CONTEXT = true;	

    return <ReactRelayContext.Provider value={ { environment: props.environment, variables: {} }}>
        {props.children}
    </ReactRelayContext.Provider>

}

export default RelayEnvironmentProvider;

```

**Comment by sibelius** [comment]
@jckw can you send a PR removing unstable_internal usage?
