### ISSUE TITLE
usePagination does't send the object ID

### ISSUE THREAD

**Issue by eMerzh** [relay-tools/relay-hooks#263]
Hello, 
sorry it will probably be a broken issue like noone like, but i have to ask 😅 
since the update to relay 16 I tend to notice a "lot" of usePagination loadNext() that trigger a refetch but without giving the object id for some reason ...  thus the query get's rejected by the server because it missed the required id ofc

i fail to understand what's going on ... 
is there someone experiencing the same thing? or has someone an explaination?

**Comment by morrys** [comment]
hi @eMerzh,
I'm working on relay v16 support, https://github.com/relay-tools/relay-hooks/pull/256

With the new release they have changed how the id is retrieved during refetch

**Comment by eMerzh** [comment]
oh ok, that might explain that .. thanks 👍
