### ISSUE TITLE
useFragment returns undefined after commitMutation mutates unrelated data

### ISSUE THREAD

**Issue by jazblueful** [relay-tools/relay-hooks#27]
Hi Lorenzo, hope you have been doing well!

Now the problem I have. Here is my (greatly simplified) code I just typed in here so there could be some syntax and null check errors.

RelayDataContext.js:
```javascript
import { createContext } from 'react';

export const RelayDataContext = createContext();
```

hooks/useUserByUsernameQuery.js:
```javascript
import { useContext } from 'react';
import { useFragment, graphql } from 'relay-hooks';
import { RelayDataContext } from '../RelayDataContext'; 

const fragmentSpec = graphql`
  fragment useUserByUsernameQuery on Query
    @argumentDefinitions(username: { type: "String!" }) {
    userByUsername(username: $username) {
      id
      email
    }
  }
`;

export const useUserByUsernameQuery = function() {
  const relayData = useContext(RelayDataContext);

  // returns undefined after commitMutation() is called
  // by pressing the 'Increment clicks' button
  return useFragment(fragmentSpec, relayData).userByUsername;
};
```

UserComponent.jsx:
```javascript
import React, { useContext } from 'react';
import { commitMutation, ReactRelayContext } from 'react-relay';
import { useUserByUsernameQuery } from './hooks/useUserByUsernameQuery';

export const UserComponent = () => {
  const user = useUserByUsernameQuery();
  const { environment } = useContext(ReactRelayContext);

  const mutate = () => {
    commitMutation(environment, {
      mutation: graphql`
        mutation UserComponentMutation {
          incrementClickCount {
            count
          }
        }
      `,
      variables: {},
      onCompleted: response => console.log(response),
      onError: error => console.error(error)
    });
  }

  return (
    <div>
      <span>Email: {user.email}</span>
      <button onClick={mutate}>Increment clicks</button> 
    </div>
  )
}
```

route.jsx:
```javascript
import React from 'react';
import { fetchQuery } from 'relay-runtime';
import { RelayDataContext } from './RelayDataContext';
import { UserComponent } from './UserComponent';

// Resulting component from this function is rendered.
export const getRouteComponent = async(environment) => {
  const query = graphql`
    query UserByUsernameQuery($username: String!) {
      ...useUserByUsernameQuery @arguments(username: $username)
    }
  `;

  const variables = {
    username: 'some-username'
  }

  const relayData = await fetchQuery(environment, query, variables)

  return (
    <RelayDataContext.Provider value={relayData}>
      <UserComponent />
    </RelayDataContext.Provider>
  );
}
```

I don't know if the problem is with relay-hooks, relay or with my own code.

I checked that after commitMutation, environment no longer contains data from the query, which explains why useFragment returns undefined, but then shouldn't there be another query to refetch the data? Why is the data from the query garbage collected in the first place after the commitMutation?

Hope you will find time to have a look into this.

**Comment by morrys** [comment]
Hi @jazblueful,
all right, thank you :)

I try to give you more information that can help you analyze the problem.
Running fetchQuery inserts data into the RecordSource but not into the Relay Store. This means that if the garbage colletor is executed and no query executed references that data, they are deleted.

Try to see who is invoking the following methods in the `ReactRelayQueryFetcher` class
`dispose();`
`disposeRequest();`

or you can debug directly here:
https://github.com/facebook/relay/blob/v5.0.0/packages/relay-runtime/store/RelayModernStore.js#L120
before performing the mutation.

**Comment by jazblueful** [comment]
Thanks @morrys for a very valuably insight into the problem

I guess I have 2 options then:
1. To use declarative api (QueryRenderer or useQuery) instead of imperative api (fetchQuery) to wrap the route component.
2. Explicitly ensure response from fetchQuery is retained.

Since my components expect data from route query to be available on first render, the 2nd option seems the way to go.

So the route.jsx would become:
```javascript
...
const relayData = await fetchQuery(environment, query, variables);
environment.getStore().retain(/* what goes here? */);
...
```
What arguments would you call retain method with?

**Comment by morrys** [comment]
exactly :)

**Comment by jazblueful** [comment]
Thanks Lorenzo! :)
