### ISSUE TITLE
Is library still maintained?

### ISSUE THREAD

**Issue by aleksandrlat** [relay-tools/relay-hooks#278]
Hello @morrys!

We appreciate this library a lot.
But it does not seem to be still maintained. For example it is 2 versions behind relay.
Currently relay-hook supports relay 16
But relay is on version 18

**Comment by morrys** [comment]
hi @aleksandrlat,
I still maintain the library but its update depends a lot on my free time available.

As soon as possible I will update the library to the latest version of relay.

**Comment by morrys** [comment]
I released two versions, one for each major release ([v9.1.0](https://github.com/relay-tools/relay-hooks/releases/tag/v9.1.0), [v9.2.0](https://github.com/relay-tools/relay-hooks/releases/tag/v9.2.0))

Basically, it was enough to adjust the test cases and update the package.json. The breaking changes introduced by relay-runtime did not affect the functionality used by relay-hooks.

Let me know if you have any problems
