### ISSUE TITLE
add useFragments

### ISSUE THREAD

**Issue by sibelius** [relay-tools/relay-hooks#3]
`useFragment` would get data from a single fragment spec
`useFragments` would get data from an object with fragment specs (this would mimic createFragmentContainer HOC)

**Comment by morrys** [comment]
`useFragment` already exists, I would change the title to "add useFragments"
In order to create `useFragments` it would be useful a pseudo code or even better an example project of a use case.

**Comment by morrys** [comment]
Hi Sibelius,
I think this issue can be closed, the current useFragment is sufficient and more in line with the official version.

If you need to use multiple fragments within the same component, you can use it multiple times:

```
   const user = useFragment (fragmentSpecUser, props.user);
   const todo = useFragment (fragmentSpecTodo, props.todo);
```

what do you think about it?
