### ISSUE TITLE
Make useQuery accept generic type to infer response?

### ISSUE THREAD

**Issue by JohannesKlauss** [relay-tools/relay-hooks#33]
Currently `useQuery`s props object is just of type `Object`.

I am using `relay-compiler-language-typescript` to create typed artifacts, so it would be really awesome if this library could support typing the response of useQuery.

The created artifact typed look something like this (just an example):
```ts
import { ConcreteRequest } from "relay-runtime";
export type IndexQueryVariables = {};
export type IndexQueryResponse = {
    readonly rootCategories: ReadonlyArray<{
        readonly id: string;
        readonly name: string;
    }> | null;
};
export type IndexQuery = {
    readonly response: IndexQueryResponse;
    readonly variables: IndexQueryVariables;
};
```

Inside a component it would be really great if we could so something like this:

```ts
const {props, error} = useQuery<IndexQuery>({
  query,
  variables: {}
});
```

Then the `useQuery` hook could assign `IndexQuery.response` to it's `props` return key.
Is this something you would consider?

**Comment by morrys** [comment]
Hi @JohannesKlauss,
proposals to improve typing are always to be considered.
We are discussing this topic in PR https://github.com/relay-tools/relay-hooks/pull/31#issuecomment-532154757
