### ISSUE TITLE
useRefetch does not reflecting.

### ISSUE THREAD

**Issue by ChintanRajpara** [relay-tools/relay-hooks#38]
Hey, I am using `useRefetch` with react-native and relay but it seems component not updating on refetched data. I am getting response from server by logging through environment file.

**Comment by morrys** [comment]
Hi @ChintanRajpara,
could you give me the query code?

thanks

**Comment by ChintanRajpara** [comment]
I had resolved it, 
i was not providing Id field to that  typeDef
