### ISSUE TITLE
is there any plan for useSubscription?

### ISSUE THREAD

**Issue by ChintanRajpara** [relay-tools/relay-hooks#39]

**Comment by taion** [comment]
Ah, shoot, is it missing here?

If you just need something to run with for now – it's a pretty simple hook to write for yourself: https://gist.github.com/taion/b7372b149d66682352cc4be6341c70fc

(Note that the above follows the old `input` pattern)

**Comment by morrys** [comment]
@taion why don't you do a PR by adding the gist? :)

**Comment by taion** [comment]
The API doesn't quite match the fragment/query hooks here; it's closer to what we have for mutations.

**Comment by ChintanRajpara** [comment]
I was not aware about ReactRelayContext, thanks for that @taion

**Comment by morrys** [comment]
Soon I will officially release version 2.0.0 where will be added useRelayEnvironment, removed from useQuery the use of dataFrom in favor of fetchPolicy  and UI refresh optimization for store-or-network & store-only policies.
