### ISSUE TITLE
2.0.0-rc.1 & ^1.3 useFragment does not work with @relay(plural: true)

### ISSUE THREAD

**Issue by akomm** [relay-tools/relay-hooks#40]
`useFragment` seem to have issues processing an array of fragments passed down from `useQuery`, when the fragment passed to `useFragment` uses `@relay(plural: true)`.

I receive: `RelayModernGraphQLTag: Expected a fragment, got {}` Error.

Same query & fragment work well with the react-relay `hoc`s.

Example:
```ts
// fragment usage

type Props = {
  items: ItemList_items$ref,
};

const ItemList: React.FC<Props> = props => {
  const items: ItemList_items = useFragment(
    graphql`
      fragment ItemList_items on Item @relay(plural: true) {
       # ...
      }
    `,
    props.items
  );
};

// query usage
const ItemListPage: React.FC<Props> = () => {
  const {props, error} = useQuery<ItemListQuery>(
    graphql`
      query ItemListQuery {
        items {
            ...ItemList_items
        }
      }
    `, {}
  );

  // ... checks, etc.

  return <ItemList items={props.items} />
};
```

**Comment by morrys** [comment]
hi @akomm ,
tonight I released version 2.0.0-rc.2 which solves a problem of subscription in the store.
In the tests I did not seem to be a problem with `plural`, could you try to update and check if the problem persists?

Thanks

**Comment by akomm** [comment]
Tested with 2.0.0-rc.3 , the issue persists.

**Comment by morrys** [comment]
Hi @akomm,
in branch 2.0.0 I modified the example project using the plural and it works correctly:
https://github.com/relay-tools/relay-hooks/blob/2.0.0/examples/relay-hook-example/todo/js/components/TodoList.js#L68

Can you give me some more information or recreate the problem?

**Comment by akomm** [comment]
I think the initial issue was fixed by the said commit. What I have now is something different that results in the same error message. I am not sure if it is responsible for the fragment error at the end, but Its now:

- `Error: RelayModernGraphQLTag: Expected a fragment, got {}.`
- followed by `this.networkSubscription.dispose is not a function`
- followed by another ``Error: RelayModernGraphQLTag: Expected a fragment, got {}.`

You just recently updated/fixed the network subscription `dispose` call, because I assume it has changed in relay-runtime@^5 ? I use `react-relay-network-modern` of which the newest version still depends on the relay-runtime^4. I guess this is at least responsible for the TypeErrror `not a function`. I look into resolving this issue with own network implementation and see if the fragment issue fixes with it.

**Comment by akomm** [comment]
- Replaced with simple fetch network. 
- Removed the network library & made sure runtime / relay is not duped somewhere in older version AND used accidentally. 

Every piece of code works as before. But whenever a component with said plural fragment is mounted, I get the 3 errors posted above. 

When I remove the `useFragment` part and wrap the component in `createFragmentContainer` instead, the error is gone.

**Comment by morrys** [comment]
`this.networkSubscription.dispose is not a function` is a library error that I shortly correct (thanks) :)

In the original version of react-relay the `store-only` and `store-or-network` policies are not yet present, in order to better manage their subscription in the store I had to re-implement part of their QueryFetcher. This change is not simple... this is the reason for the `rc` releases and not yet released definitively :)

The fact that I changed the compatibility is due to the internal `fetch` function, available from version 5.0.0.

**Comment by morrys** [comment]
What is the value of props.items returned by the useQuery?

**Comment by morrys** [comment]
@akomm, I have just released version 2.0.0-rc.4 with the dispose fix, thanks :)

**Comment by akomm** [comment]
My hands now not on code, I will try it out tomorrow. Thanks!

**Comment by morrys** [comment]
I can't in any way recreate the problem. The only way was to manually set the value of props.items = {}
```
useFragment (
     graphql`
       fragment ItemList_items on Item @relay (plural: true) {
        # ...
       }
     `,
     {}
```
In this case it is correct that error occurs because it expects the value to be an array (being plural).

**Comment by morrys** [comment]
I created a very simple example project:
https://github.com/relay-tools/relay-hooks/tree/2.0.0/examples/relay-hook-example/plural

See if there are any differences or it would be useful if you fork it and show me the error.

thanks

**Comment by akomm** [comment]
Since I use the typescript language plugin for the relay compiler, I have to compare the generated artifacts, because in the example I can not reproduce the issue. The props.items was always an array of fragments, both passed to useFragment and also received from useQuery. One of the first things I have checked multiple times. I would post ot on codesandbox but I guess I can't run relay-compiler there, but I could pre-generate the example artifacts locally and copy & paste them there...

**Comment by akomm** [comment]
The issue is not the `ref` passed to `useFragment`, but the `def`. 

The `graphql` tagged node gets converted to this artifact, example TS language:
```ts
/* tslint:disable */

import { ReaderFragment } from "relay-runtime";
export type Items_items$ref = any;
export type Items_items = ReadonlyArray<{
    readonly id: string;
    readonly displayName: string;
    readonly " $refType": Items_items$ref;
}>;

const node: ReaderFragment = {
  "kind": "Fragment",
  "name": "Items_items",
  "type": "Item",
  "metadata": {
    "plural": true
  },
  "argumentDefinitions": [],
  "selections": [
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "id",
      "args": null,
      "storageKey": null
    },
    {
      "kind": "ScalarField",
      "alias": null,
      "name": "displayName",
      "args": null,
      "storageKey": null
    }
  ]
};
(node as any).hash = '62ead0e197c94f617857410e5816ffb3';
export default node;
```

The object invariant complains about is THIS node (`def`), not the `ref`.

I tested the regular js relay-compiler and its exactly the same node/fragment that was generated, no difference also in export.

What is odd, when I leave `useQuery` but replace `useFragment` with `createFragmentContainer` both the 1. fragment def and 2. the fragment ref passed are okay and everything works. So something is not handled in `useFragment` correctly and it probably should not pass the `def` to `getFragment` the way it does.

**Comment by akomm** [comment]
@morrys I guess the `createFragmentContainer` worked with older style of import from older babel-relay-plugin. I upgraded the plugin and now also `useFragment` works! :).

Thanks!
