### ISSUE TITLE
Error: Cannot find module 'relay-runtime/lib/RelayNetworkLogger'

### ISSUE THREAD

**Issue by ricardocanelas** [relay-tools/relay-hooks#42]
https://github.com/relay-tools/relay-hooks/blob/3ae7e89ac9d3b696d63dd21f90312e80fe20ad05/examples/relay-hook-example/todo/js/app.js#L36

**Comment by sibelius** [comment]
`RelayNetworkLogger` was removed from relay v6/v7

**Comment by sibelius** [comment]
```jsx
const RelayNetworkLogger = createRelayNetworkLogger(RelayNetworkLoggerTransaction);
```
