### ISSUE TITLE
How to deal with multiple environments ?

### ISSUE THREAD

**Issue by davidgarry** [relay-tools/relay-hooks#59]
Hello,

We currently encounter a specific case where we have to deal with multiple graphql apis. We have a graphql api developed by another team and we develop our own graphql api which returns mock data. This second api allows us to do a lot of tests and to develop new features even if the real graphql api is not ready yet.

We would like to use different environments in function of the query. Some queries can already be done on the real api, but some other exist only on the mock api.

The issue is that all the methods (useQuery, useRefetch, etc.) take the environment from the context provider, and we have no solution to override that for one useQuery for example.

Is there a solution to deal with multiple environments ? The only solution I see for now is an evolution in the methods useQuery etc. to add an extra optional parameter `customEnvironment` and in the method : `const environment = customEnvironment || useRelayEnvironment();`.

What do you think ?

Thank you !

**Edit :** Issue solved with the use of networkCacheConfig.metadata object to change dynamically the url in the fetchQuery method (https://github.com/relay-tools/relay-hooks/issues/59#issuecomment-595809130)

**Comment by sibelius** [comment]
Use more then one Provider

**Comment by davidgarry** [comment]
@sibelius But how the useQuery will know which provider to use ?

**Comment by sibelius** [comment]
the closest one

**Comment by morrys** [comment]
Hi @davidgarry,
for your use case it seems sufficient to use a single environment and correctly use useQuery and the networkCacheConfig (specifically the metadata field) and manage your case at the network level.

However your request seems very similar to the solutions adopted in Apollo:
https://medium.com/open-graphql/apollo-multiple-clients-with-react-b34b571210a5

**Comment by davidgarry** [comment]
Hello @morrys 

Thank you for your answer. I will investigate deeper on the networkCacheConfig metadata 😃

**Comment by morrys** [comment]
let me know if you have any doubts and / or how you solved it :)

**Comment by davidgarry** [comment]
@morrys , thank you a lot for your help. It works perfectly with the cacheConfig.metadata object ! I'm able to change the url to use dynamically.

**Comment by uc2pac** [comment]
@davidgarry, do you mind sharing an example of how did you configure cacheConfig.metadata? I can't find cacheConfig documentation, so don't know how to configure it properly. Thanks.

**Comment by davidgarry** [comment]
Hello @uc2pac,

Here is an example (I removed some specific parts) for the configuration part :

```
import { Environment, Network, QueryResponseCache, RecordSource, Store, RequestParameters } from 'relay-runtime';

const operationKinds = {
  MUTATION: 'mutation',
  QUERY: 'query',
};

const isMutation = (operation: RequestParameters): boolean => operation.operationKind === operationKinds.MUTATION;

const isQuery = (operation: RequestParameters): boolean => operation.operationKind === operationKinds.QUERY;

let relayEnvironment = null;

const createEnvironment = (configuration) => {
  const environment = new Environment(configuration);

  // Here, we could override environment._getDataID method
  // in order to return guid field, or the combination
  // typeName and id.

  return environment;
};

export const fetchQuery = (config, cache) =>
  async (operation, variables, cacheConfig = {}) => {
    const { force = false, metadata: { customValue } = {} } = cacheConfig;
    const queryID = operation.text;
    const fromCache = cache.get(queryID, variables);

    if (isQuery(operation) && fromCache !== null && !force) {
      return fromCache;
    }

    const apiUrl = config.url;
    const headers = {
      customHeader: customValue,
    };

    const requestParams = { apiUrl, headers, operation, variables };
    const isPersistedQuerySupported = !isMutation(operation);

    const sendQueryFunction = isPersistedQuerySupported ? sendPersistedQuery : sendQuery;
    const data = await sendQueryFunction(requestParams);

    if (isQuery(operation) && data) {
      cache.set(queryID, variables, data);
    }

    if (isMutation(operation)) {
      cache.clear();
    }

    return data;
  };

export function initEnvironment({ records = {}, config } = {}) {
  const cache = new QueryResponseCache({ size: 250, ttl: 60 * 1000 });
  // Create a network layer from the fetch function
  const network = Network.create(fetchQuery(config, cache));
  const store = new Store(new RecordSource(records));

  // Make sure to create a new Relay environment for every server-side request so that data
  // isn't shared between connections (which would be bad)
  if (typeof window === 'undefined') {
    return createEnvironment({
      network,
      store,
    });
  }

  if (!relayEnvironment) {
    relayEnvironment = createEnvironment({
      network,
      store,
    });
  }

  return relayEnvironment;
}
```

And then, when you call for example fetchQuery from `react-relay`, you can send in parameter the cacheConfig object :
```
const cacheConfig = { metadata: { customValue: 'myValue' }};
const data = await fetchQuery<T>(relayEnvironment, query, variables, cacheConfig);
```

**Comment by davidgarry** [comment]
Here is the link to the CacheConfig documentation, which contains the metadata key : https://relay.dev/docs/api-reference/types/CacheConfig/#type-cacheconfig

**Comment by uc2pac** [comment]
Thank you @davidgarry. Your example really helped and saved me a lot of time.
