### ISSUE TITLE
[useQuery] Make variables optional

### ISSUE THREAD

**Issue by stramel** [relay-tools/relay-hooks#62]
When using `useQuery` it seems odd to require passing `variables` since not every query requires variables.

Similar to the `options`, we could make `variables` optional to provide a better DX.

```js
useQuery(query, {})
```

vs

```js
useQuery(query)
```

**Comment by morrys** [comment]
This would not match with relay-experimental hooks but I find the request correct.
I would propose to proceed with the implementation and also open a issue in relay repository.

**Comment by stramel** [comment]
Filed the request upstream https://github.com/facebook/relay/issues/3045
