### ISSUE TITLE
server side rendering - useQuery fails silently on server

### ISSUE THREAD

**Issue by jazblueful** [relay-tools/relay-hooks#7]
First let me say I absolutely love your work, it's very helpful in writing clean functional code.

That out of the way I'm trying to get server side rendering to work and I'm using 0.3.0 of your package which is working fine on the browser. The problem is useQuery returns 
```javascript
{ relay:
   { environment:
      RelayModernEnvironment {
        configName: undefined,
        _operationLoader: undefined,
        _network: [RelayNetworkLayer],
        _publishQueue: [RelayPublishQueue],
        _scheduler: null,
        _store: [RelayModernStore],
        unstable_internal: [Object],
        __setNet: [Function],
        DEBUG_inspect: [Function] },
     variables: { somevariable: 'somevalue' } },
  error: null,
  props: null,
  retry: null,
  cached: false }
```
on the server and RelayNetworkLayer that I passed into the environment doesn't get invoked. I tried the exact same environment, query and variables using react-relay's (4.0.0) QueryRenderer on server side and it worked so it must be the useQuery that is at fault here.

**Comment by morrys** [comment]
Thanks jazblueful :)
actually I didn't create any examples that need server side rendering.

The error is certainly caused by "useEffect" which is called only after the component has been mounted.

I would say that surely it is a topic that deserves to be investigated.

If you can set up a small sample project with ssr, it would definitely help :)

Thank you

**Comment by jazblueful** [comment]
Thank you for a quick reply :)

Yeah it makes sense. What about extracting the contents of the useEffect hook into a function and running it also outside of the useEffect hook?

I have created a minimal sample project to demonstrate the issue https://github.com/jazblueful/relay-hooks-ssr-example

Thanks

**Comment by morrys** [comment]
Hi jazblueful,
thank you for creating the project and for the suggestion.
Now I have created a branch in relay-hooks and adapted the example project to make a simple server side rendering.

I do the latest checks and release version 1.1.0

**Comment by morrys** [comment]
Perfect, relay-hooks version 1.1.0 just released.

the solution you proposed was good but not sufficient, it was necessary to also add a state in the ref to avoid a loop :)
And anyway, there are no solutions too naive :) we have plenty of time to complicate them in the future.

Now the version is available on npm and the example project in this repository uses it to perform a simple server side rendering.

I'm waiting for your news to close the issue.

Thanks again,
Lorenzo

**Comment by morrys** [comment]
In this branch https://github.com/relay-tools/relay-hooks/tree/optimization
I am implementing another solution, cleaner for the SSR and which should also reduce the number of renderings.

However, this change requires more tests to be distributed.

**Comment by jazblueful** [comment]
I'm glad you found the example project helpful.

I installed 1.1.0 and everything seems to be working accordingly now. Good job! That feeling when you finally get something useful printed to the screen after couple of days wrestling with the code :)

I'll be sure to stop by when something breaks after you have published your optimizations.

Thank you again for your amazing work!

**Comment by morrys** [comment]
`I'll be sure to stop by when something breaks after you have published your optimizations.` 

If something breaks ;)

**Comment by jazblueful** [comment]
lol, right :)

Perhaps 2 days of wrestling with my broken code has made me subconsciously pessimistic to use this kind of wording :)

**Comment by morrys** [comment]
I understand you :)
I have already verified the optimizations that make useQuery and ssr work better. Because of Murphy's law, I prefer to check better haha

For any questions you can contact me on Twitter (link in the profile) or on slack graphql.slack.com

**Comment by jazblueful** [comment]
Thank you for your wonderful support :)
