### ISSUE TITLE
Uncaught TypeError: Cannot read property '_context' of undefined

### ISSUE THREAD

**Issue by Gautierrr** [relay-tools/relay-hooks#75]
Hi,

I get this error when using the `useMutation` hook:

```
Uncaught TypeError: Cannot read property '_context' of undefined
    at Object.useContext (react.development.js?72d0:1481)
    at useMutation (useMutation.js?c207:73)
```

Seems to be relative to this line in the built version of `useMutation.js` file:
```js
var relayContext = react_1.useContext(ReactRelayContext_1.default);
```

If I remove the `.default`, it's working fine 🤔 

Do you have any idea?
Thanks!

**Comment by morrys** [comment]
Hi @Gautierrr,
are you using other hooks from this library?

**Comment by Gautierrr** [comment]
Yep, I'm also using `useFragment` and I'm facing the same issue with

**Comment by morrys** [comment]
`useRelayEnvironment `should also give you an error
How do you build the application?
Can you create a minimal example project, without graphql server, where can I check the error?

**Comment by Gautierrr** [comment]
I'm using Webpack with Babel to build my application.

Hum It's pretty hard to create a minimal example.
I can't reproduce without graphql server because I have to use `useMutation` and implement all `relay` stuff (like compiler). A simple import of `useMutation` in a file doesn't trigger the error.

**Comment by morrys** [comment]
And modify this example project?
https://github.com/relay-tools/relay-hooks/tree/master/examples/relay-hook-example/plural

**Comment by morrys** [comment]
I just updated the example with relay-hooks version 3.2.0

**Comment by Gautierrr** [comment]
I will try if I have time but it's not a big deal. It was just in case anyone had ever encountered the problem.

I forgot to mention that if I exclude `relay-hooks` from my build everything works fine.

Thank's for your prompt responses @morrys

**Comment by morrys** [comment]
What are all your relay related dependencies?

**Comment by morrys** [comment]
This problem should be solved with version 3.4.0.

In case there are still problems reopen the issue.

**Comment by Gautierrr** [comment]
No more problem, thank's @morrys ☺️ 👍

**Comment by gtrj55** [comment]
this error comes because useContext(contextName) =>contextName is undefined
you will get this error if you want to get this outside the class or function, put inside the functional component or class component, this error will resolve

**Comment by jcamato** [comment]
I have this same issue after migrating from Create React App to Next.js, and I didn't modify my context implementation at all. This is the only documentation I found with the exact "_context" undefined error. I don't have any of the hooks mentioned in this thread though.

**Comment by kdgyimah** [comment]
> I have this same issue after migrating from Create React App to Next.js, and I didn't modify my context implementation at all. This is the only documentation I found with the exact "_context" undefined error. I don't have any of the hooks mentioned in this thread though.

@jcamato I also got the same issue but just resolved it.
Check to make sure you are exporting and importing the context you created well.
In my case, I was not destructuring the created context from the file it was created in.

To be safe I later made the created context a default export so that I don't face this error if I do not destructure it


```
import React, { useEffect, useState, createContext } from "react";
import countriesContext from "./UserContext/countries";


const UserContext = createContext();

export const CountryProvider = ({ children, ...props }) => {
  /**
   * state
   */
  const [countryCode, setCountryCode] = useState("GH");

  // Get Country
  // function to get country which sets countryCode to the new Country

  return (
    <UserContext.Provider
      value={{
        location: countriesContext[countryCode],
        setLocation: setCountryCode,
        ...props,
      }}
    >
      {children}
    </UserContext.Provider>
  );
};

export default UserContext;

```

**Comment by jcamato** [comment]
@kdgyimah, that was it, thank you!

**Comment by atulpatill** [comment]
Hey I have the same issue when I'm importing data from parent Component and using it in useContext() hook. After reading this thread still not able tp understand why this is happening. 
![Screenshot (477)](https://user-images.githubusercontent.com/66541229/151711270-5fa4cc3b-2423-4da3-87de-f92d5fe6b215.png)
