### ISSUE TITLE
Way to cancel request?

### ISSUE THREAD

**Issue by CSFlorin** [relay-tools/relay-hooks#83]
I want to be able to cancel the request from a useQuery when the component it is in is unmounted. I don't see any way of doing that from the docs

**Comment by CSFlorin** [comment]
I see [this post about using AbortController to do this with Apollo](https://evilmartians.com/chronicles/aborting-queries-and-mutations-in-react-apollo) but don't see a signal parameter for useQuery that could take advantage of this

**Comment by morrys** [comment]
@CSFlorin, in relay-runtime they have just integrated this PR 
https://github.com/facebook/relay/pull/2937 that will help you to realize a solution similar to apollo.

Once released, it will also be available with hooks

While for useQuery you can use this property:
https://github.com/relay-tools/relay-hooks/blob/master/src/RelayHooksType.ts#L49

**Comment by sibelius** [comment]
check the discussion here 

https://github.com/facebook/relay/issues/2414

**Comment by CSFlorin** [comment]
@morrys Can `networkCacheConfig` cancel an in-flight request?

**Comment by morrys** [comment]
@CSFlorin inside the metadata property of networkCacheConfig you can insert the controller signal and use it in the network [as the example of the web api](https://developer.mozilla.org/en-US/docs/Web/API/AbortController)

**Comment by CSFlorin** [comment]
@morrys Thanks but I'm having a little trouble.
```
const Component: React.FC = ({ id }) => {
  const [controller, setController] = useState(new window.AbortController());

  const {
    props,
    error,
    retry,
    cached,
  } = useQuery(
    Query,
    { id },
    {
      networkCacheConfig: {
        metadata: {
          signal: controller.signal,
        },
      },
    }
  );

  useEffect(() => {
    return () => {
      console.log(`Aborted ${id}`);
      controller.abort();
    };
  }, []);

  return <></>;
};
```

And when the component unmounts, I get the console log statement, but the request continues and completes. Am I missing something?

**Comment by CSFlorin** [comment]
Actually now get that it needs to be passed to the fetch I'm doing in the relay environment using the cacheConfig there. thanks! much appreciated!

**Comment by tony** [comment]
@CSFlorin 

> Actually now get that it needs to be passed to the fetch I'm doing in the relay environment using the cacheConfig there. thanks! much appreciated!

Could you post an example of this in working condition?
