### ISSUE TITLE
useQuery error not showing graphQLErrors

### ISSUE THREAD

**Issue by CSFlorin** [relay-tools/relay-hooks#87]
I have a query responding with
```
{"errors":[{"message":"","locations":[{"line":4,"column":3}],"path":["events"]}],"data":{"events":null}}
```

```
const {error, props} = useQuery(...)
```

gives null for error and props.

How can I access the errors in the response? I see Apollo's returns
![image](https://user-images.githubusercontent.com/9855031/80651420-c2d1a480-8a2a-11ea-87bc-4cf2a3689f9d.png) and would expect similar from this.

Apologies if this is covered somewhere I missed.

**Comment by morrys** [comment]
hi @CSFlorin,
the problem is related to relay-runtime and its network.
This thread can help you: https: //github.com/facebook/relay/issues/1913

**Comment by CSFlorin** [comment]
Thanks @morrys ! Much appreciated
