### ISSUE TITLE
ES module build

### ISSUE THREAD

**Issue by earksiinni** [relay-tools/relay-hooks#88]
Any chance that you could release a version with an ES module build?

Thanks for the excellent library and all your hard work!

**Comment by morrys** [comment]
hi @earksiinni,
surely there are chances but at the moment I am busy implementing the usePreloadedQuery, in the meantime, suggestions are welcome :)

**Comment by earksiinni** [comment]
@morrys would you be open to a PR? I just issued one: https://github.com/relay-tools/relay-hooks/pull/89.

**Comment by morrys** [comment]
@earksiinni PR are always welcome :)

**Comment by morrys** [comment]
I just published the PR https://github.com/relay-tools/relay-hooks/issues/88 on the usePreloadedQuery.

I will keep it a little on hold in order to receive suggestions, in the meantime I will look at your PR.

**Comment by earksiinni** [comment]
Great, let me know if I can help in any other way :-). My PR is minimal, I don't think that it should interfere with anything else.

**Comment by morrys** [comment]
It certainly does not interfere with anything else but it is right to look at and try it before integration.

At the moment the most important help is feedback, suggestions and proposals :)

**Comment by morrys** [comment]
This issue has been resolved with the newly released version [3.6.0](https://github.com/relay-tools/relay-hooks/releases/tag/v3.6.0).
