### ISSUE TITLE
Make loadMore arguments optional

### ISSUE THREAD

**Issue by earksiinni** [relay-tools/relay-hooks#92]
In https://github.com/relay-tools/relay-hooks/blob/master/src/FragmentResolver.ts#L316-L321, `pageSize`, `observerOrCallback`, and `options` are required. However, I have been using `loadMore` just fine without them :-). We should make them optional in the typing.

**Comment by earksiinni** [comment]
Probably a similar situation for `refetchConnection`, etc.

**Comment by morrys** [comment]
Indeed these should be optional :)
https://github.com/relay-tools/relay-hooks/blob/master/src/FragmentResolver.ts#L319-L320
https://github.com/relay-tools/relay-hooks/blob/master/src/FragmentResolver.ts#L297-L298

**Comment by earksiinni** [comment]
`pageSize` can be optional, too. It has worked for me, but probably we shouldn't let `undefined` get coerced into `0` on https://github.com/relay-tools/relay-hooks/blob/master/src/FragmentResolver.ts#L335! We can make it explicit.

**Comment by morrys** [comment]
n one of the latest patches I made many changes to the fragments and probably caused typing misalignment.

In general I try to follow the same as relay:
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/react-relay/index.d.ts#L62

here it's required :)

**Comment by earksiinni** [comment]
Ah that makes sense.

**Comment by morrys** [comment]
fixed with relay-hooks version 3.5.1
https://github.com/relay-tools/relay-hooks/releases/tag/v3.5.1
