### ISSUE TITLE
PaginationFunction type doesn't make use of generic ConnectionConfig

### ISSUE THREAD

**Issue by earksiinni** [relay-tools/relay-hooks#93]
The [`PaginationFunction`](https://github.com/relay-tools/relay-hooks/blob/master/src/RelayHooksType.ts#L67-L82) type hasn't been updated to make use of the new `ConnectionConfig` generic, which accepts a props type. So if you've defined your `connectionConfig` with something like `const connectionConfig: ConnectionConfig<MyPropsType> = ...`, the pagination functions will report errors because they are using just `ConnectionConfig` without any props type, and so the props type defaults to `object` (which is incompatible with `MyPropsType`).

We should add an optional generic props type to `PaginationFunction` and pass it to `ConnectionConfig`, and `usePagination`'s signatures should be similarly updated to accept an optional props type.

**Comment by morrys** [comment]
during the week I should have time to perform both fixes:
https://github.com/relay-tools/relay-hooks/issues/92

if you want and have the possibility PR are welcome otherwise I will contact you to ask for a confirmation test :)

**Comment by earksiinni** [comment]
No problem. I'll put together a PR for both issues in the next few days @morrys. Thanks for taking a look :-)

**Comment by morrys** [comment]
fixed with relay-hooks version 3.5.1
https://github.com/relay-tools/relay-hooks/releases/tag/v3.5.1
