### ISSUE TITLE
How to send custom headers when use useQuery, useMutation?

### ISSUE THREAD

**Issue by VuongVu** [relay-tools/relay-hooks#97]

**Comment by morrys** [comment]
You can use the cacheConfig metadata parameter
https://github.com/facebook/relay/blob/master/packages/relay-runtime/mutations/commitMutation.js#L44
https://github.com/relay-tools/relay-hooks/blob/master/src/RelayHooksType.ts#L49
https://github.com/facebook/relay/pull/2937

**Comment by VuongVu** [comment]
Thank you for your reply, i will try it :smile:
