### ISSUE TITLE
Ending a subscripting

### ISSUE THREAD

**Issue by zaggaz** [relay-tools/relay-hooks#98]
Hi there, 

I'm struggling to implement disconnects in a relay subscription. What I'm planning to do, which may be wrong, is to dispose of the old subscription on disconnect, and rerender the component on connect, so useSubscription is ran again.

It would be good

E.g. something like this:
```js
const { isConnected } = useAppState();

  const viewerSub = useSubscription(
    useMemo(
      () => ({
        subscription: viewerSubscriptionSpec,
        variables: {},
      }),
      [isConnected]
    )
  );
```

I can't see to find how to dispose of the subscription. Is this even the right way?

**Comment by jplindgren** [comment]
If you look at the `useSubscription` component you will notice the dispose of the subscription is set to be called in the `useEffect` cleanup.
```
useEffect(() => {
        const { dispose } = requestSubscription(environment, config);
        return dispose;
    }, [environment, config]);
```
This would be equivalent in hooks as the `componentWillUnmount`.
So basically if I am not mistaken you do not have to do anything special. Just wait the component who called the `useSubscription`, unmount and it will execute the `dispose()` from the `useEffect` cleanup ending the subscription.
